### ISSUE TITLE
run fails due to biobox.yaml location hard coded

### ISSUE THREAD

**Issue by souptonuts** [williamdlees/IgBLAST_BioBox#2]
I followed the instructions to the letter.  Created three directories: input output and cache.  The input directory has my biobox.yaml and the fasta file with sequences.

I don't see where to specify BBX_MNTDIR.  Job fails since the default path doesn't exist on my system.

`Warning: biobox.yaml not accessible
rm: cannot remove '*': No such file or directory
--2019-02-06 02:30:24--  http://www.imgt.org/download/GENE-DB/IMGTGENEDB-ReferenceSequences.fasta-nt-WithoutGaps-F+ORF+inframeP
Resolving www.imgt.org (www.imgt.org)... 193.50.6.95
Connecting to www.imgt.org (www.imgt.org)|193.50.6.95|:80... connected.

snip

Adding sequences from FASTA; added 15 sequences in 0.000555992 seconds.
Germline file processing complete.
Traceback (most recent call last):
  File "/opt/run_igblast/RunIgblast.py", line 143, in <module>
    main(sys.argv)
  File "/opt/run_igblast/RunIgblast.py", line 46, in main
    fi = open(os.environ['BBX_MNTDIR'] + '/input/biobox.yaml')
IOError: [Errno 2] No such file or directory: '/bbx/mnt/input/biobox.yaml'

`

**Comment by williamdlees** [comment]
To work with the files parse_bb.sh and  parse_bb_win.cmd as they stand (and the examples in the readme), the directories you create should be called input_data, output_data and cache. If you rename your directories to those names, the commands should work. Alternatively you could modify the command to use your names instead.

**Comment by souptonuts** [comment]
Hello

Thank you for the clarification.  It worked as described.

I can close the bug report if you can’t do it.

**Comment by williamdlees** [comment]
Glad you got it going!
